server:
  port: 8989


#spring:
# freemarker:
#   suffix: .ftl
#   content-type: text/html
#   charset: UTF-8
#   template-loader-path: classpath:/views/


spring:
  thymeleaf:
    prefix: classpath:/html/
    cache: false

